apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel.fullname" . }}-secrets
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
type: Opaque
stringData:
  SENTINEL_GIT_TOKEN: {{ .Values.secrets.githubToken | quote }}
  SENTINEL_WEBHOOK_SECRET: {{ .Values.secrets.githubWebhookSecret | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookUrl | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
