apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: mock-store
  namespace: ml-ops-lite
spec:
  provider:
    fake:
      data:
      - key: hf-token-key
        value: "hf_mock_token_12345"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-token-external
  namespace: ml-ops-lite
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: mock-store
    kind: SecretStore
  target:
    name: hf-token
    creationPolicy: Owner
  data:
  - secretKey: HF_TOKEN
    remoteRef:
      key: hf-token-key
